// This game's spoken lines. How they're spoken (a grown-up's recording, a
// natural-voice clip or the device's voice) is in shared/voice.ts.
import { TIMER_LINES } from '../../shared/play-timer';
import { makeVoice, type Line } from '../../shared/voice';
import { sound } from './audio';
import { playerName, save } from './data';

export const LINES: Line[] = [
  { id: 'title', text: "{name}'s Ducky Bath!", when: 'Title screen' },
  { id: 'letsGo', text: 'Bath time, {name}!', when: 'Pressing play' },
  { id: 'hello', text: "Hello! I'm Ducky!", when: 'Tapping Ducky on the title' },
  { id: 'quack', text: 'Quack quack!', when: 'Tapping Ducky' },
  { id: 'tapTap', text: 'Turn on the tap!', when: 'Filling the bath' },
  { id: 'more', text: 'More water!', when: 'Filling the bath' },
  { id: 'full', text: 'The bath is full!', when: 'The bath is full' },
  { id: 'bubbleTime', text: 'Bubble time! Squeeze the bottle!', when: 'Making bubbles' },
  { id: 'popBubbles', text: 'Pop the bubbles!', when: 'Bubbles to pop' },
  { id: 'pop', text: 'Pop!', when: 'A bubble pops' },
  { id: 'sqRed', text: 'Squeak the red duck!', when: 'Pick a colour' },
  { id: 'sqOrange', text: 'Squeak the orange duck!', when: 'Pick a colour' },
  { id: 'sqBlue', text: 'Squeak the blue duck!', when: 'Pick a colour' },
  { id: 'sqPurple', text: 'Squeak the purple duck!', when: 'Pick a colour' },
  { id: 'sqPink', text: 'Squeak the pink duck!', when: 'Pick a colour' },
  { id: 'red', text: 'Red!', when: 'Naming the colour' },
  { id: 'orange', text: 'Orange!', when: 'Naming the colour' },
  { id: 'blue', text: 'Blue!', when: 'Naming the colour' },
  { id: 'purple', text: 'Purple!', when: 'Naming the colour' },
  { id: 'pink', text: 'Pink!', when: 'Naming the colour' },
  { id: 'thatRed', text: "That one's red!", when: 'Tapping another colour' },
  { id: 'thatOrange', text: "That one's orange!", when: 'Tapping another colour' },
  { id: 'thatBlue', text: "That one's blue!", when: 'Tapping another colour' },
  { id: 'thatPurple', text: "That one's purple!", when: 'Tapping another colour' },
  { id: 'thatPink', text: "That one's pink!", when: 'Tapping another colour' },
  { id: 'count', text: "Let's count the ducks!", when: 'Little ducks to count' },
  { id: 'n1', text: 'One!', when: 'Counting' },
  { id: 'n2', text: 'Two!', when: 'Counting' },
  { id: 'n3', text: 'Three!', when: 'Counting' },
  { id: 'n4', text: 'Four!', when: 'Counting' },
  { id: 'n5', text: 'Five!', when: 'Counting' },
  { id: 'muddy', text: "Oh no! Ducky's all muddy!", when: 'Mud on Ducky' },
  { id: 'scrub', text: 'Scrub scrub!', when: 'Scrubbing the mud off' },
  { id: 'clean', text: 'Squeaky clean!', when: 'All the mud gone' },
  { id: 'whereBaby', text: "Where's Baby Duck?", when: 'Baby Duck hides in the bubbles' },
  { id: 'notHere', text: 'Not in there!', when: 'Tapping the wrong bubbles' },
  { id: 'peekaboo', text: 'Peekaboo!', when: 'Finding Baby Duck' },
  { id: 'splashTap', text: 'Splash the water!', when: 'Splashing' },
  { id: 'splash', text: 'Splish splash!', when: 'Splashing' },
  { id: 'wheee', text: 'Wheee!', when: 'Splashing' },
  { id: 'plug', text: 'All clean! Pull the plug!', when: 'The end of the bath' },
  { id: 'glug', text: 'Glug glug glug!', when: 'The water going down the plughole' },
  { id: 'present', text: "A big bubble! What's inside?", when: 'A bubble floats up at the end' },
  { id: 'another', text: 'Another big bubble!', when: 'A bubble at the end, after finding every duck' },
  { id: 'newDuck', text: 'A new duck!', when: 'Popping the big bubble' },
  { id: 'd-rainbow', text: 'Rainbow Duck!', when: 'Ducks' },
  { id: 'd-princess', text: 'Princess Duck!', when: 'Ducks' },
  { id: 'd-pirate', text: 'Pirate Duck!', when: 'Ducks' },
  { id: 'd-fire', text: 'Firefighter Duck!', when: 'Ducks' },
  { id: 'd-chef', text: 'Chef Duck!', when: 'Ducks' },
  { id: 'd-frog', text: 'Froggy Duck!', when: 'Ducks' },
  { id: 'd-super', text: 'Super Duck!', when: 'Ducks' },
  { id: 'd-space', text: 'Space Duck!', when: 'Ducks' },
  { id: 'd-unicorn', text: 'Unicorn Duck!', when: 'Ducks' },
  { id: 'd-wizard', text: 'Wizard Duck!', when: 'Ducks' },
  { id: 'd-dino', text: 'Dino Duck!', when: 'Ducks' },
  { id: 'd-golden', text: 'Golden Duck!', when: 'Ducks' },
  { id: 'allItems', text: 'You found every duck, {name}!', when: 'All 12 ducks found' },
  { id: 'goShelf', text: "Let's see your ducks!", when: 'After finding a new duck' },
  { id: 'yay', text: 'Yay!', when: 'Cheering' },
  { id: 'wow', text: 'Wow!', when: 'Cheering' },
  { id: 'wellDone', text: 'Well done, {name}!', when: 'Cheering' },
  { id: 'youDidIt', text: 'You did it!', when: 'Cheering' },
  { id: 'shelf', text: 'Here are your ducks!', when: 'Opening the duck shelf' },
  { id: 'shelfEmpty', text: "No ducks yet. Let's have a bath!", when: 'The duck shelf with no ducks found yet' },
  { id: 'shelfNew', text: 'Look! A new duck!', when: 'A new duck on the shelf' },
  { id: 'sticker', text: 'A sticker for your book!', when: 'Earning a sticker for the sticker book' },
];

export const voice = makeVoice({
  lines: [...LINES, ...TIMER_LINES],
  db: 'ducky-bath-voice',
  sound,
  playerName,
  soundOn: () => save.sound,
});

export const { loadRecordings, hasRecording, stopSpeaking, sayText, say, sayAll } = voice;
