// This game's spoken lines. How they're spoken (a grown-up's recording, a
// natural-voice clip or the device's voice) is in shared/voice.ts.
import { TIMER_LINES } from '../../shared/play-timer';
import { makeVoice, type Line } from '../../shared/voice';
import { sound } from './audio';
import { playerName, save } from './data';

export const LINES: Line[] = [
  { id: 'title', text: "{name}'s Unicorn Dash!", when: 'Title screen' },
  { id: 'letsGo', text: "Let's go, {name}!", when: 'Pressing play' },
  { id: 'tapJump', text: 'Tap to jump!', when: 'Sparkle stops in front of something' },
  { id: 'jump', text: 'Jump!', when: 'Sparkle jumps' },
  { id: 'wheee', text: 'Wheee!', when: 'Sparkle jumps' },
  { id: 'upHigh', text: 'Up, up, up!', when: 'Sparkle jumps' },
  { id: 'overLog', text: 'Jump over the log!', when: 'A log in the way' },
  { id: 'overRock', text: 'Jump over the rock!', when: 'A rock in the way' },
  { id: 'overBush', text: 'Jump over the bush!', when: 'A bush in the way' },
  { id: 'catchStars', text: 'Catch the stars!', when: 'Stars in the sky' },
  { id: 'allStars', text: 'You got every star!', when: 'Catching a whole row of stars' },
  { id: 'splash', text: 'Splish splash!', when: 'Running through a puddle' },
  { id: 'overPuddle', text: 'Over the puddle!', when: 'Jumping a puddle' },
  { id: 'popRed', text: 'Pop the red balloon!', when: 'Pick a colour' },
  { id: 'popOrange', text: 'Pop the orange balloon!', when: 'Pick a colour' },
  { id: 'popYellow', text: 'Pop the yellow balloon!', when: 'Pick a colour' },
  { id: 'popBlue', text: 'Pop the blue balloon!', when: 'Pick a colour' },
  { id: 'popPurple', text: 'Pop the purple balloon!', when: 'Pick a colour' },
  { id: 'popPink', text: 'Pop the pink balloon!', when: 'Pick a colour' },
  { id: 'red', text: 'Red!', when: 'Naming the colour' },
  { id: 'orange', text: 'Orange!', when: 'Naming the colour' },
  { id: 'yellow', text: 'Yellow!', when: 'Naming the colour' },
  { id: 'blue', text: 'Blue!', when: 'Naming the colour' },
  { id: 'purple', text: 'Purple!', when: 'Naming the colour' },
  { id: 'pink', text: 'Pink!', when: 'Naming the colour' },
  { id: 'thatRed', text: "That one's red!", when: 'Tapping another colour' },
  { id: 'thatOrange', text: "That one's orange!", when: 'Tapping another colour' },
  { id: 'thatYellow', text: "That one's yellow!", when: 'Tapping another colour' },
  { id: 'thatBlue', text: "That one's blue!", when: 'Tapping another colour' },
  { id: 'thatPurple', text: "That one's purple!", when: 'Tapping another colour' },
  { id: 'thatPink', text: "That one's pink!", when: 'Tapping another colour' },
  { id: 'pop', text: 'Pop!', when: 'A balloon pops' },
  { id: 'count', text: "Fences! Let's count!", when: 'A row of little fences' },
  { id: 'n1', text: 'One!', when: 'Counting jumps' },
  { id: 'n2', text: 'Two!', when: 'Counting jumps' },
  { id: 'n3', text: 'Three!', when: 'Counting jumps' },
  { id: 'n4', text: 'Four!', when: 'Counting jumps' },
  { id: 'n5', text: 'Five!', when: 'Counting jumps' },
  { id: 'nearly', text: 'Nearly there!', when: 'Nearly at the end' },
  { id: 'present', text: "A present! What's inside?", when: 'A present at the end' },
  { id: 'another', text: 'Another present!', when: 'A present at the end, after finding them all' },
  { id: 'newThing', text: 'Something new!', when: 'Opening a present' },
  { id: 'i-rainbow', text: 'A rainbow mane!', when: 'Presents' },
  { id: 'i-flowers', text: 'A flower crown!', when: 'Presents' },
  { id: 'i-wings', text: 'Sparkly wings!', when: 'Presents' },
  { id: 'i-bow', text: 'A pretty bow!', when: 'Presents' },
  { id: 'i-partyhat', text: 'A party hat!', when: 'Presents' },
  { id: 'i-glasses', text: 'Star glasses!', when: 'Presents' },
  { id: 'i-boots', text: 'Sparkly boots!', when: 'Presents' },
  { id: 'i-goldhorn', text: 'A golden horn!', when: 'Presents' },
  { id: 'i-cape', text: 'A super cape!', when: 'Presents' },
  { id: 'i-necklace', text: 'A heart necklace!', when: 'Presents' },
  { id: 'i-bluemane', text: 'A sky blue mane!', when: 'Presents' },
  { id: 'i-crown', text: 'A royal crown!', when: 'Presents' },
  { id: 'lovely', text: 'Sparkle looks lovely!', when: 'Wearing something' },
  { id: 'goDress', text: "Let's dress up!", when: 'After finding something new' },
  { id: 'allItems', text: 'You found every present, {name}!', when: 'All 12 presents found' },
  { id: 'yay', text: 'Yay!', when: 'Cheering' },
  { id: 'wow', text: 'Wow!', when: 'Cheering' },
  { id: 'wellDone', text: 'Well done, {name}!', when: 'Cheering' },
  { id: 'youDidIt', text: 'You did it!', when: 'Cheering' },
  { id: 'neigh', text: 'Neigh!', when: 'Tapping Sparkle' },
  { id: 'hello', text: "Hi! I'm Sparkle!", when: 'Tapping Sparkle on the title' },
  { id: 'bunny', text: 'Hello, bunny!', when: 'Tapping a bunny' },
  { id: 'butterfly', text: 'A butterfly! Flutter flutter!', when: 'Tapping a butterfly' },
  { id: 'dressUp', text: 'Dress up Sparkle!', when: 'Opening dressing up' },
  { id: 'dressEmpty', text: "Nothing here yet. Let's dash!", when: 'Dressing up with nothing found yet' },
  { id: 'dressNew', text: 'Look! Something new!', when: 'Something new to wear' },
  { id: 'sticker', text: 'A sticker for your book!', when: 'Earning a sticker for the sticker book' },
];

export const voice = makeVoice({
  lines: [...LINES, ...TIMER_LINES],
  db: 'unicorn-dash-voice',
  sound,
  playerName,
  soundOn: () => save.sound,
});

export const { loadRecordings, hasRecording, stopSpeaking, sayText, say, sayAll } = voice;
