// This game's spoken lines. How they're spoken (a grown-up's recording, a
// natural-voice clip or the device's voice) is in shared/voice.ts.
import { makeVoice, type Line } from '../../shared/voice';
import { sound } from './audio';
import { playerName, save } from './data';

export { Recorder } from '../../shared/voice';

export const LINES: Line[] = [
  { id: 'title', text: "{name}'s Bakery!", when: 'Title screen' },
  { id: 'letsBake', text: "Let's bake, {name}!", when: 'Pressing play' },
  { id: 'bear', text: 'Hello, Bear!', when: 'Bear comes in' },
  { id: 'hippo', text: 'Hello, Hippo!', when: 'Hippo comes in' },
  { id: 'bunny', text: 'Hello, Bunny!', when: 'Bunny comes in' },
  { id: 'piggy', text: 'Hello, Piggy!', when: 'Piggy comes in' },
  { id: 'elephant', text: 'Hello, Elephant!', when: 'Elephant comes in' },
  { id: 'dino', text: 'Hello, Dino!', when: 'Dino comes in' },
  { id: 'owl', text: 'Hello, Owl!', when: 'Owl comes in' },
  { id: 'cat', text: 'Hello, Kitty!', when: 'Kitty comes in' },
  { id: 'wish', text: 'I would like…', when: 'A customer says what they want' },
  { id: 'please', text: 'Please!', when: 'After the customer’s wish' },
  { id: 'whatBake', text: 'What shall we bake?', when: 'Choosing cake, cupcake or cookie' },
  { id: 'cake', text: 'Cake!', when: 'Naming things' },
  { id: 'cupcake', text: 'Cupcake!', when: 'Naming things' },
  { id: 'cookie', text: 'Cookie!', when: 'Naming things' },
  { id: 'eggs', text: 'Crack the eggs!', when: 'Three eggs to tap' },
  { id: 'rollAway', text: 'Whoops! Come back, egg!', when: 'Silly: an egg rolls away' },
  { id: 'sugar', text: 'Shake in the sugar!', when: 'The sugar shaker (three taps)' },
  { id: 'sweet', text: 'Mmm, sweet!', when: 'After the sugar' },
  { id: 'flour', text: 'Tap the flour!', when: 'Pouring the flour' },
  { id: 'achoo', text: 'Achoo! Bless you!', when: 'Silly: the mouse sneezes' },
  { id: 'pickColour', text: 'Pick a colour!', when: 'Choosing a colour' },
  { id: 'pink', text: 'Pink!', when: 'Naming colours' },
  { id: 'yellow', text: 'Yellow!', when: 'Naming colours' },
  { id: 'blue', text: 'Blue!', when: 'Naming colours' },
  { id: 'green', text: 'Green!', when: 'Naming colours' },
  { id: 'purple', text: 'Purple!', when: 'Naming colours' },
  { id: 'choc', text: 'Chocolate!', when: 'Naming colours' },
  { id: 'stir', text: 'Stir, stir, stir!', when: 'Stirring the bowl' },
  { id: 'yumBatter', text: 'Mmm! Tasty!', when: 'Silly: the mouse tastes the batter' },
  { id: 'pickShape', text: 'Pick a shape!', when: 'Choosing a shape' },
  { id: 'round', text: 'Circle!', when: 'Naming shapes' },
  { id: 'heart', text: 'Heart!', when: 'Naming shapes' },
  { id: 'star', text: 'Star!', when: 'Naming shapes' },
  { id: 'oven', text: 'Close the oven!', when: 'Putting it in the oven' },
  { id: 'waiting', text: 'Tick, tock…', when: 'Waiting for the oven' },
  { id: 'ding', text: 'Ding! Open the oven!', when: 'The oven is done' },
  { id: 'puffy', text: 'Whoa! So big!', when: 'Silly: it puffs up too much' },
  { id: 'icing', text: 'Pick the icing!', when: 'Choosing icing' },
  { id: 'sprinkles', text: 'Shake the sprinkles!', when: 'Sprinkles' },
  { id: 'onTop', text: 'What goes on top?', when: 'Choosing a topping' },
  { id: 'cherry', text: 'A cherry!', when: 'Cherry on top' },
  { id: 'strawberry', text: 'A strawberry!', when: 'Strawberry on top' },
  { id: 'candles', text: "Candles! Let's count!", when: 'Candles on top' },
  { id: 'blow', text: 'Blow out the candles!', when: 'After three candles' },
  { id: 'serve', text: 'Tap to give it!', when: 'Serving the customer' },
  { id: 'yummy', text: 'Mmm! Yummy!', when: 'A customer eats' },
  { id: 'justRight', text: 'Just what I wanted!', when: 'It matched the wish' },
  { id: 'thankYou', text: 'Thank you, {name}!', when: 'The customer says thanks' },
  { id: 'byeBye', text: 'Bye-bye!', when: 'The customer leaves' },
  { id: 'shop', text: 'Your bakery shop!', when: 'Opening the shop window' },
  { id: 'shopEmpty', text: "The shelves are empty. Let's bake!", when: 'Shop with no treats yet' },
  { id: 'shopNew', text: 'Look! Something new!', when: 'A shop surprise unlocked' },
  { id: 'nightShop', text: 'Night night, bakery!', when: 'Shop switched to night' },
  { id: 'dayShop', text: 'Good morning, bakery!', when: 'Shop switched to day' },
  { id: 'yay', text: 'Yay!', when: 'Cheering' },
  { id: 'n1', text: 'One!', when: 'Counting' },
  { id: 'n2', text: 'Two!', when: 'Counting' },
  { id: 'n3', text: 'Three!', when: 'Counting' },
  { id: 'sticker', text: 'A sticker for your book!', when: 'Earning a sticker for the sticker book' },
];

export const { loadRecordings, hasRecording, recordingCount, saveRecording, deleteRecording, stopSpeaking, sayText, say, sayAll, previewLine, lineText } = makeVoice({
  lines: LINES,
  db: 'little-bakery-voice',
  sound,
  playerName,
  soundOn: () => save.sound,
});
