// Extracts the handful of Microsoft Fluent Emoji (MIT licence) the game uses
// into src/sprites.ts as data URIs, so the build stays a single offline file.
// Run with: npm run sprites
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { getIconData, iconToHTML, iconToSVG } from '@iconify/utils';

const require = createRequire(import.meta.url);
const icons = require('@iconify-json/fluent-emoji/icons.json');

// Sprites are used only in round buttons and the recipe strip, where emoji-style
// icons look right. Everything in the scenes is drawn in code (src/art.ts).
const NAMES = ['egg', 'candy', 'glass-of-milk', 'spoon', 'fire', 'sparkles', 'cherries', 'strawberry', 'candle'];

let out = `// Generated by scripts/sprites.mjs from Microsoft Fluent Emoji (MIT licence,
// https://github.com/microsoft/fluentui-emoji). Do not edit by hand.
export const SPRITES = {\n`;
for (const name of NAMES) {
  const data = getIconData(icons, name);
  if (!data) throw new Error(`Missing icon: ${name}`);
  const { attributes, body } = iconToSVG(data, { height: 128 });
  const svg = iconToHTML(body, attributes);
  // Lightly-encoded (not base64) so the build gzips well.
  const uri = `data:image/svg+xml,${svg.replace(/"/g, "'").replace(/[%#<>{}\n]/g, (c) => encodeURIComponent(c))}`;
  out += `  '${name}': ${JSON.stringify(uri)},\n`;
}
out += `} as const;\n\nexport type SpriteName = keyof typeof SPRITES;\n`;
writeFileSync(new URL('../src/sprites.ts', import.meta.url), out);
console.log(`Wrote ${NAMES.length} sprites (${(out.length / 1024).toFixed(0)} KB)`);
