// Extracts the handful of Microsoft Fluent Emoji (MIT licence) the game uses
// into src/sprites.ts as data URIs, so the build stays a single offline file.
// Run with: npm run sprites
import { writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { getIconData, iconToHTML, iconToSVG } from '@iconify/utils';

const require = createRequire(import.meta.url);
const icons = require('@iconify-json/fluent-emoji/icons.json');

const NAMES = [
  // food
  'strawberry', 'tangerine', 'banana', 'pear', 'blueberries', 'grapes', 'watermelon', 'maple-leaf',
  // garden flowers
  'hibiscus', 'cherry-blossom', 'tulip', 'sunflower', 'blossom', 'rose',
  // garden friends & things
  'mushroom', 'frog', 'rabbit', 'bird', 'deciduous-tree', 'red-apple', 'fountain', 'rainbow', 'snail',
  'honeybee', 'house-with-garden', 'four-leaf-clover', 'seedling', 'herb',
  // sky
  'glowing-star', 'sun-with-face', 'crescent-moon', 'shooting-star',
];

let out = `// Generated by scripts/sprites.mjs from Microsoft Fluent Emoji (MIT licence,
// https://github.com/microsoft/fluentui-emoji). Do not edit by hand.
export const SPRITES = {\n`;
for (const name of NAMES) {
  const data = getIconData(icons, name);
  if (!data) throw new Error(`Missing icon: ${name}`);
  const { attributes, body } = iconToSVG(data, { height: 128 });
  const svg = iconToHTML(body, attributes);
  // Lightly-encoded (not base64) so the build gzips well.
  const uri = `data:image/svg+xml,${svg.replace(/"/g, "'").replace(/[%#<>{}\n]/g, (c) => encodeURIComponent(c))}`;
  out += `  '${name}': ${JSON.stringify(uri)},\n`;
}
out += `} as const;\n\nexport type SpriteName = keyof typeof SPRITES;\n`;
writeFileSync(new URL('../src/sprites.ts', import.meta.url), out);
console.log(`Wrote ${NAMES.length} sprites (${(out.length / 1024).toFixed(0)} KB)`);
