// This game's spoken lines. How they're spoken (a grown-up's recording, a
// natural-voice clip or the device's voice) is in shared/voice.ts.
import { makeVoice, type Line } from '../../shared/voice';
import { sound } from './audio';
import { playerName, save } from './data';

export { Recorder } from '../../shared/voice';

export const LINES: Line[] = [
  { id: 'title', text: "{name}'s Leapy Pond!", when: 'Title screen' },
  { id: 'letsHop', text: "Let's hop, {name}!", when: 'Pressing play' },
  { id: 'tapPad', text: 'Tap a lily pad!', when: 'Waiting for a hop' },
  { id: 'hop', text: 'Hop!', when: 'Hoppy jumps' },
  { id: 'wheee', text: 'Wheee!', when: 'Hoppy jumps' },
  { id: 'boing', text: 'Boing!', when: 'Hoppy jumps' },
  { id: 'fly', text: 'Slurp! A yummy fly!', when: 'Hoppy catches a fly' },
  { id: 'splash', text: 'Splish splash!', when: 'Tapping the water' },
  { id: 'fishy', text: 'Fishy!', when: 'A fish jumps' },
  { id: 'findRed', text: 'Find the red flower!', when: 'Pick a colour' },
  { id: 'findOrange', text: 'Find the orange flower!', when: 'Pick a colour' },
  { id: 'findYellow', text: 'Find the yellow flower!', when: 'Pick a colour' },
  { id: 'findBlue', text: 'Find the blue flower!', when: 'Pick a colour' },
  { id: 'findPurple', text: 'Find the purple flower!', when: 'Pick a colour' },
  { id: 'findPink', text: 'Find the pink flower!', when: 'Pick a colour' },
  { id: 'red', text: 'Red!', when: 'Naming the colour' },
  { id: 'orange', text: 'Orange!', when: 'Naming the colour' },
  { id: 'yellow', text: 'Yellow!', when: 'Naming the colour' },
  { id: 'blue', text: 'Blue!', when: 'Naming the colour' },
  { id: 'purple', text: 'Purple!', when: 'Naming the colour' },
  { id: 'pink', text: 'Pink!', when: 'Naming the colour' },
  { id: 'thatRed', text: "That one's red!", when: 'Tapping another colour' },
  { id: 'thatOrange', text: "That one's orange!", when: 'Tapping another colour' },
  { id: 'thatYellow', text: "That one's yellow!", when: 'Tapping another colour' },
  { id: 'thatBlue', text: "That one's blue!", when: 'Tapping another colour' },
  { id: 'thatPurple', text: "That one's purple!", when: 'Tapping another colour' },
  { id: 'thatPink', text: "That one's pink!", when: 'Tapping another colour' },
  { id: 'count', text: "Stepping stones! Let's count!", when: 'A row of little hops' },
  { id: 'n1', text: 'One!', when: 'Counting hops' },
  { id: 'n2', text: 'Two!', when: 'Counting hops' },
  { id: 'n3', text: 'Three!', when: 'Counting hops' },
  { id: 'n4', text: 'Four!', when: 'Counting hops' },
  { id: 'n5', text: 'Five!', when: 'Counting hops' },
  { id: 'nearly', text: 'Nearly there!', when: 'One hop to go' },
  { id: 'whoIs', text: "Who's that?", when: 'Someone waits at the end' },
  { id: 'newFriend', text: 'A new friend!', when: 'Meeting someone new' },
  { id: 'm-duck', text: 'A duckling! Quack quack!', when: 'Pond friends' },
  { id: 'm-turtle', text: 'Hello, turtle!', when: 'Pond friends' },
  { id: 'm-dragonfly', text: 'A dragonfly! Zoom zoom!', when: 'Pond friends' },
  { id: 'm-snail', text: 'A snail! Slowly, slowly!', when: 'Pond friends' },
  { id: 'm-fish', text: 'A goldfish! Blub blub!', when: 'Pond friends' },
  { id: 'm-ladybird', text: 'A spotty ladybird!', when: 'Pond friends' },
  { id: 'm-tadpoles', text: 'Tadpoles! Wiggle wiggle!', when: 'Pond friends' },
  { id: 'm-butterfly', text: 'A butterfly! Flutter flutter!', when: 'Pond friends' },
  { id: 'm-bee', text: 'A bumblebee! Buzz buzz!', when: 'Pond friends' },
  { id: 'm-swan', text: 'A beautiful swan!', when: 'Pond friends' },
  { id: 'm-otter', text: 'An otter! Splish splosh!', when: 'Pond friends' },
  { id: 'm-babyfrog', text: 'A baby frog! Ribbit!', when: 'Pond friends' },
  { id: 'comeHome', text: "Let's take them home!", when: 'After meeting a friend' },
  { id: 'allFriends', text: 'You found every friend, {name}!', when: 'All 12 friends met' },
  { id: 'yay', text: 'Yay!', when: 'Cheering' },
  { id: 'wow', text: 'Wow!', when: 'Cheering' },
  { id: 'wellDone', text: 'Well done, {name}!', when: 'Cheering' },
  { id: 'youDidIt', text: 'You did it!', when: 'Cheering' },
  { id: 'ribbit', text: 'Ribbit!', when: 'Tapping Hoppy' },
  { id: 'hoppy', text: "Hi! I'm Hoppy!", when: 'Tapping Hoppy on the title' },
  { id: 'myPond', text: 'Your pond friends!', when: 'Opening your pond' },
  { id: 'pondEmpty', text: "No friends yet. Let's hop!", when: 'Your pond with nobody in it yet' },
  { id: 'pondNew', text: 'Look! Someone new!', when: 'A new friend in your pond' },
  { id: 'sticker', text: 'A sticker for your book!', when: 'Earning a sticker for the sticker book' },
];

export const { loadRecordings, hasRecording, recordingCount, saveRecording, deleteRecording, stopSpeaking, sayText, say, sayAll, previewLine, lineText } = makeVoice({
  lines: LINES,
  db: 'leapy-pond-voice',
  sound,
  playerName,
  soundOn: () => save.sound,
});
