// This game's spoken lines. How they're spoken (a grown-up's recording, a
// natural-voice clip or the device's voice) is in shared/voice.ts.
//
// Letters are said by their names ("S is for snake!"). A grown-up who'd
// rather use letter sounds ("sss is for snake!") can record those lines in
// their own voice.
import { TIMER_LINES } from '../../shared/play-timer';
import { makeVoice, type Line } from '../../shared/voice';
import { sound } from './audio';
import { playerName, save } from './data';

export const LINES: Line[] = [
  { id: 'title', text: "{name}'s Postie Pip!", when: 'Title screen' },
  { id: 'letsGo', text: "Let's take the post, {name}!", when: 'Pressing play' },
  { id: 'hello', text: "Hello! I'm Pip the postie!", when: 'Tapping Pip on the title' },
  { id: 'hiPip', text: 'Parcels for everyone!', when: 'Tapping Pip' },
  { id: 'newLetter', text: 'A new letter!', when: 'Meeting a new letter' },
  { id: 'knock', text: 'Knock on the door!', when: 'Meeting a new letter' },
  { id: 'draw', text: "Let's draw it! Tap the dots!", when: 'Drawing a letter' },
  { id: 'lastParcel', text: 'The last parcel is for you, {name}!', when: 'The end of the round' },
  { id: 'whatInside', text: "What's inside?", when: 'The end of the round' },
  { id: 'newFriend', text: 'A new letter friend!', when: 'Learning a new letter' },
  { id: 'allFriends', text: 'You know every letter, {name}!', when: 'All 26 letters learned' },
  { id: 'thankYou', text: 'Thank you, Pip!', when: 'A parcel delivered' },
  { id: 'l-s', text: 'S!', when: 'Letters' },
  { id: 'l-a', text: 'A!', when: 'Letters' },
  { id: 'l-t', text: 'T!', when: 'Letters' },
  { id: 'l-m', text: 'M!', when: 'Letters' },
  { id: 'l-p', text: 'P!', when: 'Letters' },
  { id: 'l-o', text: 'O!', when: 'Letters' },
  { id: 'l-c', text: 'C!', when: 'Letters' },
  { id: 'l-h', text: 'H!', when: 'Letters' },
  { id: 'l-d', text: 'D!', when: 'Letters' },
  { id: 'l-f', text: 'F!', when: 'Letters' },
  { id: 'l-e', text: 'E!', when: 'Letters' },
  { id: 'l-b', text: 'B!', when: 'Letters' },
  { id: 'l-r', text: 'R!', when: 'Letters' },
  { id: 'l-n', text: 'N!', when: 'Letters' },
  { id: 'l-g', text: 'G!', when: 'Letters' },
  { id: 'l-i', text: 'I!', when: 'Letters' },
  { id: 'l-l', text: 'L!', when: 'Letters' },
  { id: 'l-k', text: 'K!', when: 'Letters' },
  { id: 'l-u', text: 'U!', when: 'Letters' },
  { id: 'l-j', text: 'J!', when: 'Letters' },
  { id: 'l-w', text: 'W!', when: 'Letters' },
  { id: 'l-z', text: 'Z!', when: 'Letters' },
  { id: 'l-y', text: 'Y!', when: 'Letters' },
  { id: 'l-v', text: 'V!', when: 'Letters' },
  { id: 'l-q', text: 'Q!', when: 'Letters' },
  { id: 'l-x', text: 'X!', when: 'Letters' },
  { id: 'is-s', text: 'S is for snake!', when: 'The snake at the S house' },
  { id: 'is-a', text: 'A is for ant!', when: 'The ant at the A house' },
  { id: 'is-t', text: 'T is for tiger!', when: 'The tiger at the T house' },
  { id: 'is-m', text: 'M is for mouse!', when: 'The mouse at the M house' },
  { id: 'is-p', text: 'P is for pig!', when: 'The pig at the P house' },
  { id: 'is-o', text: 'O is for octopus!', when: 'The octopus at the O house' },
  { id: 'is-c', text: 'C is for cat!', when: 'The cat at the C house' },
  { id: 'is-h', text: 'H is for hen!', when: 'The hen at the H house' },
  { id: 'is-d', text: 'D is for dog!', when: 'The dog at the D house' },
  { id: 'is-f', text: 'F is for fox!', when: 'The fox at the F house' },
  { id: 'is-e', text: 'E is for elephant!', when: 'The elephant at the E house' },
  { id: 'is-b', text: 'B is for bear!', when: 'The bear at the B house' },
  { id: 'is-r', text: 'R is for rabbit!', when: 'The rabbit at the R house' },
  { id: 'is-n', text: 'N is for narwhal!', when: 'The narwhal at the N house' },
  { id: 'is-g', text: 'G is for goat!', when: 'The goat at the G house' },
  { id: 'is-i', text: 'I is for iguana!', when: 'The iguana at the I house' },
  { id: 'is-l', text: 'L is for lion!', when: 'The lion at the L house' },
  { id: 'is-k', text: 'K is for koala!', when: 'The koala at the K house' },
  { id: 'is-u', text: 'U is for unicorn!', when: 'The unicorn at the U house' },
  { id: 'is-j', text: 'J is for jellyfish!', when: 'The jellyfish at the J house' },
  { id: 'is-w', text: 'W is for walrus!', when: 'The walrus at the W house' },
  { id: 'is-z', text: 'Z is for zebra!', when: 'The zebra at the Z house' },
  { id: 'is-y', text: 'Y is for yak!', when: 'The yak at the Y house' },
  { id: 'is-v', text: 'V is for vulture!', when: 'The vulture at the V house' },
  { id: 'is-q', text: 'Q is for quail!', when: 'The quail at the Q house' },
  { id: 'is-x', text: 'X is for x-ray fish!', when: 'The x-ray fish at the X house' },
  { id: 'find-s', text: 'Find the letter S!', when: 'A parcel for S' },
  { id: 'find-a', text: 'Find the letter A!', when: 'A parcel for A' },
  { id: 'find-t', text: 'Find the letter T!', when: 'A parcel for T' },
  { id: 'find-m', text: 'Find the letter M!', when: 'A parcel for M' },
  { id: 'find-p', text: 'Find the letter P!', when: 'A parcel for P' },
  { id: 'find-o', text: 'Find the letter O!', when: 'A parcel for O' },
  { id: 'find-c', text: 'Find the letter C!', when: 'A parcel for C' },
  { id: 'find-h', text: 'Find the letter H!', when: 'A parcel for H' },
  { id: 'find-d', text: 'Find the letter D!', when: 'A parcel for D' },
  { id: 'find-f', text: 'Find the letter F!', when: 'A parcel for F' },
  { id: 'find-e', text: 'Find the letter E!', when: 'A parcel for E' },
  { id: 'find-b', text: 'Find the letter B!', when: 'A parcel for B' },
  { id: 'find-r', text: 'Find the letter R!', when: 'A parcel for R' },
  { id: 'find-n', text: 'Find the letter N!', when: 'A parcel for N' },
  { id: 'find-g', text: 'Find the letter G!', when: 'A parcel for G' },
  { id: 'find-i', text: 'Find the letter I!', when: 'A parcel for I' },
  { id: 'find-l', text: 'Find the letter L!', when: 'A parcel for L' },
  { id: 'find-k', text: 'Find the letter K!', when: 'A parcel for K' },
  { id: 'find-u', text: 'Find the letter U!', when: 'A parcel for U' },
  { id: 'find-j', text: 'Find the letter J!', when: 'A parcel for J' },
  { id: 'find-w', text: 'Find the letter W!', when: 'A parcel for W' },
  { id: 'find-z', text: 'Find the letter Z!', when: 'A parcel for Z' },
  { id: 'find-y', text: 'Find the letter Y!', when: 'A parcel for Y' },
  { id: 'find-v', text: 'Find the letter V!', when: 'A parcel for V' },
  { id: 'find-q', text: 'Find the letter Q!', when: 'A parcel for Q' },
  { id: 'find-x', text: 'Find the letter X!', when: 'A parcel for X' },
  { id: 'pic-s', text: 'A parcel for the snake!', when: 'A parcel with a picture on' },
  { id: 'pic-a', text: 'A parcel for the ant!', when: 'A parcel with a picture on' },
  { id: 'pic-t', text: 'A parcel for the tiger!', when: 'A parcel with a picture on' },
  { id: 'pic-m', text: 'A parcel for the mouse!', when: 'A parcel with a picture on' },
  { id: 'pic-p', text: 'A parcel for the pig!', when: 'A parcel with a picture on' },
  { id: 'pic-o', text: 'A parcel for the octopus!', when: 'A parcel with a picture on' },
  { id: 'pic-c', text: 'A parcel for the cat!', when: 'A parcel with a picture on' },
  { id: 'pic-h', text: 'A parcel for the hen!', when: 'A parcel with a picture on' },
  { id: 'pic-d', text: 'A parcel for the dog!', when: 'A parcel with a picture on' },
  { id: 'pic-f', text: 'A parcel for the fox!', when: 'A parcel with a picture on' },
  { id: 'pic-e', text: 'A parcel for the elephant!', when: 'A parcel with a picture on' },
  { id: 'pic-b', text: 'A parcel for the bear!', when: 'A parcel with a picture on' },
  { id: 'pic-r', text: 'A parcel for the rabbit!', when: 'A parcel with a picture on' },
  { id: 'pic-n', text: 'A parcel for the narwhal!', when: 'A parcel with a picture on' },
  { id: 'pic-g', text: 'A parcel for the goat!', when: 'A parcel with a picture on' },
  { id: 'pic-i', text: 'A parcel for the iguana!', when: 'A parcel with a picture on' },
  { id: 'pic-l', text: 'A parcel for the lion!', when: 'A parcel with a picture on' },
  { id: 'pic-k', text: 'A parcel for the koala!', when: 'A parcel with a picture on' },
  { id: 'pic-u', text: 'A parcel for the unicorn!', when: 'A parcel with a picture on' },
  { id: 'pic-j', text: 'A parcel for the jellyfish!', when: 'A parcel with a picture on' },
  { id: 'pic-w', text: 'A parcel for the walrus!', when: 'A parcel with a picture on' },
  { id: 'pic-z', text: 'A parcel for the zebra!', when: 'A parcel with a picture on' },
  { id: 'pic-y', text: 'A parcel for the yak!', when: 'A parcel with a picture on' },
  { id: 'pic-v', text: 'A parcel for the vulture!', when: 'A parcel with a picture on' },
  { id: 'pic-q', text: 'A parcel for the quail!', when: 'A parcel with a picture on' },
  { id: 'pic-x', text: 'A parcel for the x-ray fish!', when: 'A parcel with a picture on' },
  { id: 'goStreet', text: "Let's see your street!", when: 'After learning a new letter' },
  { id: 'street', text: 'Here is your street!', when: 'Opening your street' },
  { id: 'streetEmpty', text: "Nobody here yet. Let's take the post!", when: 'Your street with no letters learned yet' },
  { id: 'streetNew', text: 'Look! A new letter friend!', when: 'A new house on your street' },
  { id: 'yay', text: 'Yay!', when: 'Cheering' },
  { id: 'wow', text: 'Wow!', when: 'Cheering' },
  { id: 'wellDone', text: 'Well done, {name}!', when: 'Cheering' },
  { id: 'youDidIt', text: 'You did it!', when: 'Cheering' },
  { id: 'sticker', text: 'A sticker for your book!', when: 'Earning a sticker for the sticker book' },
];

export const voice = makeVoice({
  lines: [...LINES, ...TIMER_LINES],
  db: 'postie-pip-voice',
  sound,
  playerName,
  soundOn: () => save.sound,
});

export const { loadRecordings, hasRecording, stopSpeaking, sayText, say, sayAll } = voice;
